services:
  stanza:
    container_name: togogenome_stanza_production
    build:
      context: .
      dockerfile: Dockerfile
    image: togogenome_stanza_production
    user: ${UID:-0}:${DOCKER_GID:-0}
    volumes:
      - ${PWD}:/usr/src/app
    ports:
      - "19292:9292"
    networks:
      - togogenome_production
networks:
  togogenome_production: